version: 0.2
env:
  variables:
    ENV_NAME: Production
phases:
  install:
    runtime_versions:
      nodejs: 18
    commands:
      - echo 'installing the packages'
      - npm install
  pre_build:
    commands:
      - echo 'testing the application'
      - npm test
  build:
    commands:
      - echo ' building the application'
      - npm run build
      - echo 'build successfull'
